# Generated by Django 5.2.4 on 2025-08-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_duration_event_event_type_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_official',
            field=models.BooleanField(default=False, help_text='Evento oficial publicado por staff'),
        ),
    ]
