# Generated by Django 5.2.4 on 2025-08-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(default=100, help_text='Maximum number of participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_official',
            field=models.BooleanField(default=False, help_text='Evento oficial de la institución'),
        ),
    ]
