# Generated by Django 5.2.4 on 2025-08-25 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_max_capacity_alter_event_is_official'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization that owns this event', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
