# Generated by Django 5.2.4 on 2025-10-06 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_eventcomment_parent_comment_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='events.eventcomment'),
        ),
    ]
