# Generated by Django 5.2.4 on 2025-10-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20251006_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcomment',
            name='parent_comment',
        ),
    ]
