# Generated by Django 5.2.4 on 2025-10-06 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_eventcomment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='events.eventcomment'),
        ),
    ]
