# Generated by Django 5.2.4 on 2025-11-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventcomment_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment_reply', 'Comment Reply'), ('event_update', 'Event Update'), ('registration_confirmed', 'Registration Confirmed'), ('unregistration_confirmed', 'Unregistration Confirmed'), ('event_reminder_1day', 'Event Reminder - 1 Day')], default='comment_reply', max_length=25),
        ),
    ]
