# Generated by Django 5.2.4 on 2025-11-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment_reply', 'Comment Reply'), ('event_update', 'Event Update'), ('registration_confirmed', 'Registration Confirmed'), ('unregistration_confirmed', 'Unregistration Confirmed'), ('event_registration', 'Event Registration'), ('event_created', 'Event Created'), ('event_deleted', 'Event Deleted')], default='comment_reply', max_length=25),
        ),
    ]
