# Generated by Django 5.2.4 on 2025-10-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved')], default='pending', max_length=20),
        ),
    ]
