"""
Django settings for spherelinkproject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG se configura desde variable de entorno, por defecto True para desarrollo/EC2
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# Usar variable de entorno si está disponible, sino usar fallback para desarrollo/EC2
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-!i1&mdr(_!kq^rkl*&i29_fzv+^h%7mkjtzu3a4ir=kli6@7-h')

# ALLOWED_HOSTS - obtener desde variable de entorno o usar wildcard para desarrollo/EC2
# Para EC2: agregar la IP pública de la instancia, ej: ALLOWED_HOSTS = ['54.123.45.67', 'localhost']
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',') if os.environ.get('ALLOWED_HOSTS') else ['*']


# Application definition

INSTALLED_APPS = [
    'registration',  # Moved to top so custom templates override admin templates
    'events',
    'profiles',
    'organizations',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'spherelinkproject.middleware.SessionTimeoutMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'organizations.middleware.SuperAdminRedirectMiddleware',
    'organizations.middleware.MessageCleanupMiddleware',
]

ROOT_URLCONF = 'spherelinkproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'profiles.context_processors.user_profile',
                'profiles.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'spherelinkproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Detectar si estamos en AWS (usando RDS) o en desarrollo local
if 'RDS_DB_NAME' in os.environ:
    # Configuración para AWS RDS (PostgreSQL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }
else:
    # Configuración para desarrollo local (SQLite)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login and Logout URLs
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/events/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Message Framework Configuration
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
MESSAGE_LEVEL = 20  # INFO level

# Session Configuration
SESSION_COOKIE_AGE = 1800  # 30 minutes in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True  # Update session on every request

# Email Configuration
# Para desarrollo: usar console backend (muestra emails en consola)
# Para producción: usar SMTP backend (envía emails reales)

# Obtener credenciales de email de variables de entorno
# Para desarrollo/EC2: usar valores por defecto si no hay variables de entorno
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'spherelinkevents@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'qbxajscgdzidajhb')  # Fallback para desarrollo/EC2

# Si hay credenciales configuradas, usar SMTP. Si no, usar console backend
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    # Configuración SMTP para envío real de emails
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = True
    print(f"\n{'='*60}")
    print(f"EMAIL CONFIGURADO: Usando SMTP Backend")
    print(f"Servidor: {EMAIL_HOST}:{EMAIL_PORT}")
    print(f"Usuario: {EMAIL_HOST_USER}")
    print(f"{'='*60}\n")
else:
    # Configuración para desarrollo (muestra emails en consola)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = True
    print(f"\n{'='*60}")
    print(f"EMAIL EN MODO DESARROLLO: Usando Console Backend")
    print(f"Los emails se mostraran en la consola del servidor")
    print(f"Para enviar emails reales, configura EMAIL_HOST_USER y EMAIL_HOST_PASSWORD")
    print(f"{'='*60}\n")

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER if EMAIL_HOST_USER else 'noreply@spherelink.com')
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'spherelinkevents@gmail.com')